name: "activate-msvc"
description: >
  Activates the MSVC compiler. Also installs and activates the Intel Fortran
  compiler, since gfortran doesn't work with MSVC. This action should only be
  run on Windows runners.

# this action doesn't need any permissions for reading from or writing to the
# repository itself
permissions:
  contents: none

runs:
  using: "composite"
  steps:
    - name: Install Fortran
      id: install-fortran
      # this hash specifies version 1.8.0
      uses: fortran-lang/setup-fortran@d2ba6ea44297a24407def2f6e117954d844a5368
      with:
        compiler: 'intel'
        version: '2025.2'
        update-environment: false

      # If we'd let the previous step update the environment variables, it
      # would've also set the C and C++ compilers, and we only want the Fortran
      # compiler. Instead, we manually set the Fortran compiler environment
      # variable here.
    - name: Activate Fortran
      shell: bash
      run: echo FC=${{ steps.install-fortran.outputs.fc }} >> $GITHUB_ENV

    - name: Activate MSVC
      # this hash specifies 1.13.0
      uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756
