name: "build-external"
description: "Either builds an external dependency or fetches it from cache"

inputs:
  library:
    description: "Name of the dependency to build"
    required: true
  version:
    description: "Version of the dependency to build"
    required: true

outputs:
  path:
    description: "Path to the installed dependency"
    # FIXME: collapse this with cache-check.path
    value: build/external/${{ inputs.library }}-${{ inputs.version }}

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: cache-check
      with:
        path: build/external/${{ inputs.library }}-${{ inputs.version }}
        key: ${{ inputs.library }}-${{ inputs.version }}-${{ runner.os }}-${{ matrix.build-output }}

    - name: Build library
      if: ${{ steps.cache-check.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        cmake --build build/external/ --target ${{ inputs.library }} \
              --config ${{ env.BUILD_TYPE }} \
        && \
        C:/Windows/system32/cmd.exe /C \
        'cd /D D:/a/sketcher/sketcher/build/external/qt-prefix/src/qt-build/qtbase/src/3rdparty/libpng && D:/a/sketcher/sketcher/build/external/qt-prefix/src/qt-build/qtbase/bin/syncqt.exe @D:/a/sketcher/sketcher/build/external/qt-prefix/src/qt-build/qtbase/src/3rdparty/libpng/PngPrivate_syncqt_args'

    - name: syncqt
      if: ${{ steps.cache-check.outputs.cache-hit != 'true' && matrix.os == 'windows-latest'}}
      shell: cmd
      run: |
        cd /D D:/a/sketcher/sketcher/build/external/qt-prefix/src/qt-build/qtbase/src/3rdparty/libpng && \
        D:/a/sketcher/sketcher/build/external/qt-prefix/src/qt-build/qtbase/bin/syncqt.exe @D:/a/sketcher/sketcher/build/external/qt-prefix/src/qt-build/qtbase/src/3rdparty/libpng/PngPrivate_syncqt_args
