name: "build-external"
description: "Either builds an external dependency or fetches it from cache"

inputs:
  library:
    description: "Name of the dependency to build"
    required: true
  version:
    description: "Version of the dependency to build"
    required: true
  host-build:
    description: "Whether to build a host library for use in cross-compiling (e.g. a Linux build of Qt that gets used during the WASM build process)"
    required: false
    default: false

outputs:
  path:
    description: "Absolute path to the installed dependency"
    value: ${{ github.workspace }}/${{ steps.vars.outputs.lib-dir }}

runs:
  using: "composite"
  steps:
    - name: Determine the build directories
      id: vars
      shell: bash
      run: |
        BUILD_DIR="build/external${{ inputs.host-build == 'true' && '/host' || '' }}"
        echo "build-dir=${BUILD_DIR}" >> $GITHUB_OUTPUT
        echo "lib-dir=${BUILD_DIR}/${{ inputs.library }}-${{ inputs.version }}" >> $GITHUB_OUTPUT

    - uses: actions/cache@v4
      id: cache-check
      with:
        path: ${{ steps.vars.outputs.lib-dir }}
        # Regenerate the cache if the version OR external/CMakeLists.txt changes
        key: ${{ inputs.library }}-${{ inputs.version }}-${{ runner.os }}-${{ matrix.build-output }}${{ inputs.host-build == 'true' && '-host' || '' }}-${{ hashFiles('external/CMakeLists.txt') }}

    - name: Build library
      if: steps.cache-check.outputs.cache-hit != 'true'
      # The Windows Qt build fails if we try to use bash, since it shells out to
      # cmd and doesn't protect the path backslashes from bash
      shell: ${{ runner.os == 'windows' && 'cmd' || 'bash' }}
      env:
        use-emsdk: ${{ matrix.build-output == 'wasm' && inputs.host-build == 'false' && 'true' }}
        # cmd uses ^ for escaping newlines instead of
        endl: ${{ runner.os == 'windows' && '^' || '\' }}
      run: |
        ${{ env.use-emsdk == 'true' && 'source emsdk_env.sh && ' || '' }}${{env.endl}}
        cmake --build ${{ steps.vars.outputs.build-dir }} --verbose${{env.endl}}
              --target ${{ inputs.library }}${{env.endl}}
              --config ${{ env.BUILD_TYPE }}