name: "build-external"
description: "Either builds an external dependency or fetches it from cache"

inputs:
  library:
    description: "Name of the dependency to build"
    required: true
  version:
    description: "Version of the dependency to build"
    required: true
  force_host:
    required: false
    default: ${{ true }}

outputs:
  path:
    description: "Path to the installed dependency"
    # FIXME: collapse this with cache-check.path
    value: ${{ github.workspace }}/build/external/${{ inputs.library }}-${{ inputs.version }}
    
runs:
  using: "composite"
  steps:
    - uses: actions/cache@v4
      id: cache-check
      env:
        env_force_host: ${{ inputs.force_host }}
        env_not_force_host: ${{ !inputs.force_host }}
        env_from_json_force_host: ${{ fromJson(inputs.force_host) }}
        env_force_host_compare_str_true: ${{ inputs.force_host == 'true' }}
        env_force_host_compare_str_false: ${{ inputs.force_host == 'false' }}
        env_force_host_compare_true: ${{ inputs.force_host == true }}
        env_force_host_compare_false: ${{ inputs.force_host == false }}
        use_emsdk: ${{ matrix.build_output == 'wasm' && inputs.force_host == 'false'}}
        lib_build_dir: build/external/${{ inputs.force_host && 'host/' || '' }}
      with:
        path: ${{ env.lib_build_dir }}${{ inputs.library }}-${{ inputs.version }}
        key: ${{ inputs.library }}-${{ inputs.version }}-${{ runner.os }}-${{ inputs.force_host && 'host' || matrix.build_output }}
        

    - name: Build library
      if: ${{ steps.cache-check.outputs.cache-hit != 'true' }}
      # The Windows Qt build fails if we try to use bash, since it shells out to
      # cmd and doesn't protect the path backslashes from bash
      shell: ${{ runner.os == 'windows' && 'cmd' || 'bash' }}
      env:
        use_emsdk: ${{ matrix.build_output == 'wasm' && inputs.force_host == false}}
        lib_build_dir: build/external/${{ inputs.force_host == true && 'host/' || '' }}
      # don't put escaped newlines in this command, since it needs to be
      # runnable in both bash and cmd (which uses ^ to escape newlines)
      run: ${{ env.use_emsdk == 'true' && 'source emsdk_env.sh && ' || '' }}cmake --build ${{ env.lib_build_dir }} --verbose --target ${{ inputs.library }} --config ${{ env.BUILD_TYPE }}