inputs:
  platform:
    description: 'platform on which we are building'
    required: true
  deps_sha:
    description: 'commit hash of the last change to the dependencies file'
    required: true
  library:
    description: 'Name of the dependency to build'
    required: true
  version:
    description: 'Version of the dependency to build'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check for a cached build
      id: cache-check
      uses: actions/cache@v3
      with:
        path: ./dependencies/${{ inputs.platform }}_${{ inputs.deps_sha }}_${{ inputs.library }}
        key: ${{ inputs.platform }}_${{ inputs.deps_sha }}_${{ inputs.library }}

    - name: Setup the build environment
      if: steps.cache-check.outputs.cache-hit != 'true'
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: 'latest'
        environment-file: dependencies/${{ inputs.platform }}_environment.yml
        init-shell: bash
        cache-environment: true
        post-cleanup: 'none'

    - name: Run build script
      if: ${{ steps.cache-check.outputs.cache-hit != 'true' && success() }}
      shell: bash -l {0}
      run: |
        # if [ -f ${CONDA_PREFIX}/etc/conda/activate.d/vs2019_compiler_vars.bat }}.sh ]; then
        #   cmd.exe /c ${CONDA_PREFIX}/etc/conda/activate.d/vs2019_compiler_vars.bat
        # fi
        cat $CONDARC
        export
        if [ -f dependencies/build_${{ inputs.library }}.sh ]; then
          ./dependencies/build_${{ inputs.library }}.sh ${{ inputs.platform }} ${{ inputs.version }} ${{ inputs.deps_sha }}
        else
          echo Failed to find an appropriate script to build ${{ inputs.library }} on ${{ inputs.platform }}
          exit 1
        fi

