#pragma once

#include <QDialog>
#include <QVBoxLayout>
#include <QDialogButtonBox>

#include "schrodinger/sketcher/definitions.h"
#include "schrodinger/sketcher/dialog/custom_title_bar.h"

namespace schrodinger
{
namespace sketcher
{

class SKETCHER_API ModalDialog : public QDialog
{
    Q_OBJECT
  public:
    ModalDialog(QWidget* parent = nullptr,
                Qt::WindowFlags f = Qt::WindowFlags());
    ~ModalDialog();

  protected:
    /**
     * This base class creates the initial UI for the dialog, but the derived
     * class is responsible for adding the contents of the dialog by calling
     * this method.
     *
     * Note: The UIs are QWidgets, not QDialogs, because they are being inserted
     * into a QDialog.
     *
     * If the QWidget contains a QDialogButtonBox, the dialog's accept and
     * reject signals are connected to the ModalDialog's accept and reject
     * slots.
     *
     * @param ui The `Ui::` class generated by `uic` from a `.ui` file.
     */
    template <typename T> void setupDialogUI(T& ui)
    {
        QWidget* dlg_contents = new QWidget(this);
        ui.setupUi(dlg_contents);
        m_dlg_layout->addWidget(dlg_contents);
        setWindowTitle(dlg_contents->windowTitle());

        auto* button_box = dlg_contents->findChild<QDialogButtonBox*>();
        if (button_box != nullptr) {
            connect(button_box, &QDialogButtonBox::accepted, this,
                    &ModalDialog::accept);
            connect(button_box, &QDialogButtonBox::rejected, this,
                    &ModalDialog::reject);
        }
    };

    QVBoxLayout* m_dlg_layout = nullptr;

  private:
    // NOTE: modal dialogs that use `exec()` are problematic in the
    // WebAssembly (WASM) build, and will not return values. Explicitly enforce
    // dialogs inherited from this class to be modal and use show.
    using QDialog::exec;
    using QDialog::open;

    /**
     * (WASM) Update the custom title bar's title when the window title changes
     */
    void onWindowTitleChanged(const QString& newTitle);

    CustomTitleBar* m_title_bar = nullptr;
};

} // namespace sketcher
} // namespace schrodinger
