#pragma once

#include <string>
#include <vector>

namespace fasta
{

static const std::vector<std::string> INVALID_PEPTIDE_EXAMPLES{
    "AA;",
    ">\n>\nAA",
    "",
    R"(-A-APL*)",       // sequence with stops
    ";some desc\nAAPL", // sequence with comment
    R"(; Comment c1
; Comment c12
>1ETT_L, 49 bases, 1742 checksum.
; Comment c2
; Comment c12
TSEDHFQPFFNEKTFGAGEADCGLRPLFEKKQVQDQTEKELFESYIEGR
; Comment c3
; Comment c12
>1ETT_H, 259 bases, 9922 checksum.
; Comment c4
; Comment c12
IVEGQDAEVGLSPWQVMLFRKSPQELLCGASLISDRWVLTAAHCLLYPPW
; Comment c5
; Comment c12
DKNFTVDDLLVRIGKHSRTRYERKVEKISMLDKIYIHPRYNWKENLDRDI
; Comment c6
; Comment c12
ALLKLKRPIELSDYIHPVCLPDKQTAAKLLHAGFKGRVTGWGNRRETWTT
; Comment c7
; Comment c12
SVAEVQPSVLQVVNLPLVERPVCKASTRIRITDNMFCAGYKPGEGKRGDA
; Comment c8
; Comment c12
CEGDSGGPFVMKSPYNNRWYQMGIVSWGEGCDRDGKYGFYTHVFRLKKWI
; Comment c9
; Comment c12
QKVIDRLGS
; Comment c10
; Comment c12
>1ETT_Z, 49 bases, 1742 checksum.
; Comment c11
; Comment c12
TSEDHFQPFFNEKTFGAGEADCGLRPLFEKKQVQDQTEKELFESYIEGR
; Comment c12
; Comment c13)",
};

static const std::vector<std::string> INVALID_NUCLEOTIDE_EXAMPLES{
    "AAE",
    R"(-A-APL*)",      // sequence with stops
    ";some desc\nAAC", // sequence with comment

};

static const std::vector<std::string> VALID_PEPTIDE_EXAMPLES{
    ">\nAAPL",                        // single peptide sequence
    ">\n-A-APL",                      // sequence with missing monomers
    ">\nARGXCKXEDA",                  // sequence with empty annotation
    ">some description\nAAA",         // sequence with annptation
    ">some description\nAAA\nDDD",    // single multi-line sequence
    ">some description\nAAA\n\nDDD",  // single multi-line sequence
    ">some description\nAAA\n>\nDDD", // multiple sequences

    // Bispecific_-_Pembrolizumab_rcsb_pdb_5DK3_Dupilumab_bispecific.fasta
    R"(
>5DK3_1|Chains A, C[auth F]|Light Chain|Homo sapiens (9606)
EIVLTQSPATLSLSPGERATLSCRASKGVSTSGYSYLHWYQQKPGQAPRLLIYLASYLESGVPARFSGSGSGTDFTLTISSLEPEDFAVYYCQHSRDLPLTFGGGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC
>5DK3_2|Chains B, D[auth G]|Heavy Chain|Homo sapiens (9606)
QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGINPSNGGTNFNEKFKNRVTLTTDSSTTTAYMELKSLQFDDTAVYYCARRDYRFDMGFDYWGQGTTVTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTKTYTCNVDHKPSNTKVDKRVESKYGPPCPPCPAPEFLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQFNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQEEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLS
>9669H|dupilumab|Homo sapiens||H-GAMMA-4 (VH (1-125) [D1] + CH1 (126-223) [D2] + CH2 (236-345) [D3] + CH3 (346-450) [D4])|||||||451|451|||MW undefined|MW undefined|
EVQLVESGGGLEQPGGSLRLSCAGSGFTFRDYAMTWVRQAPGKGLEWVSSISGSGGNTYY
ADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKDRLSITIRPRYYGLDVWGQGTT
VTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPA
VLQSSGLYSLSSVVTVPSSSLGTKTYTCNVDHKPSNTKVDKRVESKYGPPCPPCPAPEFL
GGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQ
FNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQ
EEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDKS
RWQEGNVFSCSVMHEALHNHYTQKSLSLSLG
>9669L|dupilumab|Homo sapiens||L-KAPPA (V-KAPPA (1-112) [D1] + C-KAPPA (113-219) [D2])|||||||219|219|||MW undefined|MW undefined|
DIVMTQSPLSLPVTPGEPASISCRSSQSLLYSIGYNYLDWYLQKSGQSPQLLIYLGSNRA
SGVPDRFSGSGSGTDFTLKISRVEAEDVGFYYCMQALQTPYTFGQGTKLEIKRTVAAPSV
FIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSL
SSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC)",

    // Fab2_-_rcsb_pdb_1B4J.fasta
    R"(
>1B4J_1|Chain A[auth L]|ANTIBODY|Homo sapiens (9606)
NIVMTQSPKSMYVSIGERVTLSCKASENVDTYVSWYQQKPEQSPKLLIYGASNRYTGVPDRFTGSGSATDFTLTISSVQAEDLADYHCGQSYNYPFTFGSGTKLEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC
>1B4J_2|Chain B[auth H]|ANTIBODY|Homo sapiens (9606)
QVQLQQPGADLVMPGAPVKLSCLASGYIFTSSWINWVKQRPGRGLEWIGRIDPSDGEVHYNQDFKDKATLTVDKSSSTAYIQLNSLTSEDSAVYYCARGFLPWFADWGQGTLVTVSAASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSC
>1B4J_3|Chain C[auth L]|ANTIBODY|Homo sapiens (9606)
NIVMTQSPKSMYVSIGERVTLSCKASENVDTYVSWYQQKPEQSPKLLIYGASNRYTGVPDRFTGSGSATDFTLTISSVQAEDLADYHCGQSYNYPFTFGSGTKLEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC
>1B4J_4|Chain D[auth H]|ANTIBODY|Homo sapiens (9606)
QVQLQQPGADLVMPGAPVKLSCLASGYIFTSSWINWVKQRPGRGLEWIGRIDPSDGEVHYNQDFKDKATLTVDKSSSTAYIQLNSLTSEDSAVYYCARGFLPWFADWGQGTLVTVSAASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSC)",

    // Fv_-_Pembrolizumab_rcsb_pdb_5DK3.fasta
    R"(
>5DK3_1|Chains A, C[auth F]|Light Chain|Homo sapiens (9606)
EIVLTQSPATLSLSPGERATLSCRASKGVSTSGYSYLHWYQQKPGQAPRLLIYLASYLESGVPARFSGSGSGTDFTLTISSLEPEDFAVYYCQHSRDLPLTFGGGTKVEIK
>5DK3_2|Chains B, D[auth G]|Heavy Chain|Homo sapiens (9606)
QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGINPSNGGTNFNEKFKNRVTLTTDSSTTTAYMELKSLQFDDTAVYYCARRDYRFDMGFDYWGQGTTVTVSS)",

    // Fv_-_abituzumab.fasta
    R"(
>abituzumab|HC
QVQLQQSGGELAKPGASVKVSCKASGYTFSSFWMHWVRQAPGQGLEWIGYINPRSGYTEYNEIFRDKATMTTDTSTSTAY
MELSSLRSEDTAVYYCASFLGRGAMDYWGQGTTVTVSS
>abituzumab|LC
DIQMTQSPSSLSASVGDRVTITCRASQDISNYLAWYQQKPGKAPKLLIYYTSKIHSGVPSRFSGSGSGTDYTFTISSLQP
EDIATYYCQQGNTFPYTFGQGTKVEIK)",

    // Monospecific_Ab_-_Dupilumab.fasta
    R"(
>9669L|dupilumab|Homo sapiens||L-KAPPA (V-KAPPA (1-112) [D1] + C-KAPPA (113-219) [D2])|||||||219|219|||MW undefined|MW undefined|
DIVMTQSPLSLPVTPGEPASISCRSSQSLLYSIGYNYLDWYLQKSGQSPQLLIYLGSNRA
SGVPDRFSGSGSGTDFTLKISRVEAEDVGFYYCMQALQTPYTFGQGTKLEIKRTVAAPSV
FIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSL
SSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC
>9669H|dupilumab|Homo sapiens||H-GAMMA-4 (VH (1-125) [D1] + CH1 (126-223) [D2] + CH2 (236-345) [D3] + CH3 (346-450) [D4])|||||||451|451|||MW undefined|MW undefined|
EVQLVESGGGLEQPGGSLRLSCAGSGFTFRDYAMTWVRQAPGKGLEWVSSISGSGGNTYY
ADSVKGRFTISRDNSKNTLYLQMNSLRAEDTAVYYCAKDRLSITIRPRYYGLDVWGQGTT
VTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPA
VLQSSGLYSLSSVVTVPSSSLGTKTYTCNVDHKPSNTKVDKRVESKYGPPCPPCPAPEFL
GGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQ
FNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQ
EEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDKS
RWQEGNVFSCSVMHEALHNHYTQKSLSLSLG)",

    // Monospecific_Ab_-_Pembrolizumab_rcsb_pdb_5DK3.fasta
    R"(
>5DK3_1|Chains A, C[auth F]|Light Chain|Homo sapiens (9606)
EIVLTQSPATLSLSPGERATLSCRASKGVSTSGYSYLHWYQQKPGQAPRLLIYLASYLESGVPARFSGSGSGTDFTLTISSLEPEDFAVYYCQHSRDLPLTFGGGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC
>5DK3_2|Chains B, D[auth G]|Heavy Chain|Homo sapiens (9606)
QVQLVQSGVEVKKPGASVKVSCKASGYTFTNYYMYWVRQAPGQGLEWMGGINPSNGGTNFNEKFKNRVTLTTDSSTTTAYMELKSLQFDDTAVYYCARRDYRFDMGFDYWGQGTTVTVSSASTKGPSVFPLAPCSRSTSESTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTKTYTCNVDHKPSNTKVDKRVESKYGPPCPPCPAPEFLGGPSVFLFPPKPKDTLMISRTPEVTCVVVDVSQEDPEVQFNWYVDGVEVHNAKTKPREEQFNSTYRVVSVLTVLHQDWLNGKEYKCKVSNKGLPSSIEKTISKAKGQPREPQVYTLPPSQEEMTKNQVSLTCLVKGFYPSDIAVEWESNGQPENNYKTTPPVLDSDGSFFLYSRLTVDKSRWQQGNVFSCSVMHEALHNHYTQKSLSLS)",

    // Monospecific_Ab_-_anti-cmyc_antibody_9E10_rcsb_pdb_2OR9.fasta
    R"(
>2OR9_1|Chains A[auth L], C[auth M]|Monoclonal anti-c-myc antibody 9E10|Mus musculus (10090)
DIVLTQSPASLAVSLGQRATISCRASESVDNYGFSFMNWFQQKPGQPPKLLIYAISNRGSGVPARFSGSGSGTDFSLNIHPVEEDDPAMYFCQQTKEVPWTFGGGTKLEIKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC
>2OR9_2|Chains B[auth H], D[auth I]|Monoclonal anti-c-myc antibody 9E10|Mus musculus (10090)
EVHLVESGGDLVKPGGSLKLSCAASGFTFSHYGMSWVRQTPDKRLEWVATIGSRGTYTHYPDSVKGRFTISRDNDKNALYLQMNSLKSEDTAMYYCARRSEFYYYGNTYYYSAMDYWGQGASVTVSSAKTTPPSVYPLAPGSAAQTNSMVTLGCLVKGYFPEPVTVTWNSGSLSSGVHTFPAVLQSDLYTLSSSVTVPSSTWPSETVTCNVAHPASSTKVDKKIVPRD)",

    // Multiple_Fv_in_one_FASTA_sample_set_heavyandlight.fasta
    R"(
>abituzumab:H VH domain
QVQLQQSGGELAKPGASVKVSCKASGYTFSSFWMHWVRQAPGQGLEWIGYINPRSGYTEY
NEIFRDKATMTTDTSTSTAYMELSSLRSEDTAVYYCASFLGRGAMDYWGQGTTVTVSS
>abituzumab:L VL domain
DIQMTQSPSSLSASVGDRVTITCRASQDISNYLAWYQQKPGKAPKLLIYYTSKIHSGVPS
RFSGSGSGTDYTFTISSLQPEDIATYYCQQGNTFPYTFGQGTKVEIK

>abrilumab:H VH domain
QVQLVQSGAEVKKPGASVKVSCKVSGYTLSDLSIHWVRQAPGKGLEWMGGFDPQDGETIY
AQKFQGRVTMTEDTSTDTAYMELSSLKSEDTAVYYCATGSSSSWFDPWGQGTLVTVSS
>abrilumab:L VL domain
DIQMTQSPSSVSASVGDRVTITCRASQGISSWLAWYQQKPGKAPKLLIYGASNLESGVPS
RFSGSGSGTDFTLTISSLQPEDFANYYCQQANSFPWTFGQGTKVEIK

>adalimumab:H VH domain
EVQLVESGGGLVQPGRSLRLSCAASGFTFDDYAMHWVRQAPGKGLEWVSAITWNSGHIDY
ADSVEGRFTISRDNAKNSLYLQMNSLRAEDTAVYYCAKVSYLSTASSLDYWGQGTLVTVS
S
>adalimumab:L VL domain
DIQMTQSPSSLSASVGDRVTITCRASQGIRNYLAWYQQKPGKAPKLLIYAASTLQSGVPS
RFSGSGSGTDFTLTISSLQPEDVATYYCQRYNRAPYTFGQGTKVEIK

>alemtuzumab:H VH domain
QVQLQESGPGLVRPSQTLSLTCTVSGFTFTDFYMNWVRQPPGRGLEWIGFIRDKAKGYTT
EYNPSVKGRVTMLVDTSKNQFSLRLSSVTAADTAVYYCAREGHTAAPFDYWGQGSLVTVS
S
>alemtuzumab:L VL domain
DIQMTQSPSSLSASVGDRVTITCKASQNIDKYLNWYQQKPGKAPKLLIYNTNNLQTGVPS
RFSGSGSGTDFTFTISSLQPEDIATYYCLQHISRPRTFGQGTKVEIK

>alirocumab:H VH domain
EVQLVESGGGLVQPGGSLRLSCAASGFTFNNYAMNWVRQAPGKGLDWVSTISGSGGTTNY
ADSVKGRFIISRDSSKHTLYLQMNSLRAEDTAVYYCAKDSNWGNFDLWGRGTLVTVSS
>alirocumab:L VL domain
DIVMTQSPDSLAVSLGERATINCKSSQSVLYRSNNRNFLGWYQQKPGQPPNLLIYWASTR
ESGVPDRFSGSGSGTDFTLTISSLQAEDVAVYYCQQYYTTPYTFGQGTKLEIK)",
};

static const std::vector<std::string> VALID_NUCLEOTIDE_EXAMPLES{
    ">\nAAC",                         // single nucleotide sequence
    ">\n-A-AC",                       // sequence with missing monomers
    ">\nATGNCUNCA",                   // sequence with empty annotation
    ">some description\nAAA",         // sequence with annotation
    ">some description\nAAA\nCCC",    // single multi-line sequence
    ">some description\nAAA\n\nCCC",  // single multi-line sequence
    ">some description\nAAA\n>\nCCC", // multiple sequences
};

} // namespace fasta
