name: "generate-helm-gallery"
description: "Generate HELM molecule gallery using sketcher WASM and deploy to GitHub Pages"

inputs:
  artifact-name:
    description: "Name of the WASM artifact to download"
    required: true
  gallery-name:
    description: "Unique identifier for naming the gallery artifact"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if monomer_coordgen files changed
      id: check-changes
      shell: bash
      run: |
        if [ -n "${{ github.base_ref }}" ] && [ "${{ github.event_name }}" = "pull_request" ]; then
          git fetch origin ${{ github.base_ref }}
          if git diff --name-only origin/${{ github.base_ref }}...HEAD | \
             grep -qE "(monomer_coordgen\.(cpp|h)|test/testfiles/helm-gallery/.*\.csv)"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Download WASM build artifacts
      if: steps.check-changes.outputs.changed == 'true'
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: build/wasm

    - name: Install Playwright and generate gallery
      if: steps.check-changes.outputs.changed == 'true'
      shell: bash
      run: |
        npm install playwright
        npx playwright install chromium --with-deps
        node .github/scripts/generate_helm_gallery.mjs \
          test/testfiles/helm-gallery/*.csv \
          --wasm-dir build/wasm \
          --output helm_gallery.html

    - name: Upload gallery as artifact
      if: steps.check-changes.outputs.changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: helm-gallery-${{ inputs.gallery-name }}
        path: helm_gallery.html

    - name: Prepare Pages deployment
      if: steps.check-changes.outputs.changed == 'true'
      shell: bash
      run: |
        mkdir -p pages-site
        cp helm_gallery.html pages-site/index.html

    - name: Upload Pages artifact
      if: steps.check-changes.outputs.changed == 'true'
      uses: actions/upload-pages-artifact@v3
      with:
        path: pages-site

    - name: Deploy to GitHub Pages
      if: steps.check-changes.outputs.changed == 'true'
      uses: actions/deploy-pages@v4
      id: deployment

    - name: Comment on PR with gallery link
      if: steps.check-changes.outputs.changed == 'true' && github.event.pull_request.number != ''
      uses: actions/github-script@v7
      with:
        script: |
          const galleryUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}`;
          const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

          const commentBody = [
            '## HELM Gallery',
            '',
            `**[View Gallery](${galleryUrl})** | [Download Artifact](${artifactUrl})`
          ].join('\n');

          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: commentBody
          });
