name: Build Sketcher
on: [push]
jobs:
  build:
    steps:
      - uses: actions/cache@v3

      - name: Install latest CMake
        uses: lukka/get-cmake@latest

      - name: Run CMake
        uses: lukka/run-cmake@v10