name: Sketcher CI
on: [push]
jobs:
  build-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
      - name: Run CMake
        working-directory: ./build
        run: cmake ..
      - name: Build
        run: cmake --build build
      - name: Run Tests
        run: ctest --test-dir build
