name: Sketcher CI
on:
    workflow_dispatch: ~
    push: ~
#      branches:
#        - 'main'
#        - 'releases/**'


jobs:

    generate_jobs:
        runs-on: ubuntu-latest
        outputs:
          jobs: ${{ steps.job-gen.outputs.jobs }}
        steps:

        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Import dependencies
          run: |
            {
                echo 'DEPENDENCIES_JSON<<EOF'
                cat dependencies.json
                echo -e '\nEOF'
            } >> "$GITHUB_ENV"

        - name: Build strategy matrix
          id: job-gen
          uses: actions/github-script@v6
          with:
            script: |
                const deps = ${{ env.DEPENDENCIES_JSON }}
                jobs = {}
                jobs.os = ["ubuntu-latest", "macos-latest", "windows-latest"]
                jobs.library = []
                jobs.include = []
                for (const dep of deps) {
                    jobs.library.push(dep.library)
                    jobs.include.push({
                        library: dep.library,
                        version: dep.version,
                    })
                }
                console.log(jobs)
                core.setOutput('jobs', JSON.stringify(jobs))

    base_deps:
        needs: generate_jobs
        strategy:
            matrix: ${{ fromJson(needs.generate_jobs.outputs.jobs) }}

        runs-on: ${{ matrix.os }}
        steps:

        - name: Log dep_name
          run: echo "dep_name = ${{ matrix.library }}\n version = ${{ matrix.version }}"
